#!/bin/bash

# Script to add new files to Xcode project
# Run this from the project root directory

echo "New files to add to Xcode project:"
echo "=================================="
echo ""
echo "Swift Files to add to 'chordispeak' target:"
echo "- chordispeak/PrivacyPolicyView.swift"
echo "- chordispeak/TermsOfServiceView.swift"
echo "- chordispeak/SettingsView.swift"
echo "- chordispeak/AboutView.swift"
echo "- chordispeak/NetworkManager.swift"
echo "- chordispeak/OnboardingView.swift"
echo "- chordispeak/AccessibilityExtensions.swift"
echo ""
echo "Storyboard Files to add:"
echo "- chordispeak/LaunchScreen.storyboard"
echo ""
echo "Entitlements File to add:"
echo "- chordispeak/chordispeak.entitlements"
echo "  (Set as Code Signing Entitlements in Build Settings)"
echo ""
echo "Documentation Files (add to project but not to target):"
echo "- AppStoreMetadata.md"
echo "- PreSubmissionChecklist.md"
echo ""
echo "=================================="
echo ""
echo "To add these files in Xcode:"
echo "1. Right-click on 'chordispeak' folder in Xcode"
echo "2. Select 'Add Files to \"chordispeak\"...'"
echo "3. Select all the Swift files listed above"
echo "4. Make sure 'chordispeak' target is checked"
echo "5. Click 'Add'"
echo ""
echo "For the entitlements file:"
echo "1. Add it to the project as above"
echo "2. In project settings, go to 'Signing & Capabilities'"
echo "3. Set 'Code Signing Entitlements' to 'chordispeak/chordispeak.entitlements'"
echo ""
echo "For LaunchScreen.storyboard:"
echo "1. Add it to the project"
echo "2. It should automatically be recognized as the launch screen"
echo "3. If not, set it in Info.plist under UILaunchStoryboardName"

# Make script executable
chmod +x "$0"