#!/bin/bash

# Script to help add Swift files to Xcode project
echo "🎵 ChordiSpeak iOS App - File Addition Helper"
echo "=============================================="
echo ""
echo "This script will help you add the new Swift files to your Xcode project."
echo ""
echo "Files to add to Xcode project:"
echo "1. Models.swift"
echo "2. ChordiSpeakAPI.swift" 
echo "3. ChordiSpeakViewModel.swift"
echo "4. AudioFilePicker.swift"
echo "5. ProcessingProgressView.swift"
echo "6. ChordProgressionView.swift"
echo ""
echo "Instructions:"
echo "1. Open chordispeak.xcodeproj in Xcode"
echo "2. In the Project Navigator, right-click on the 'chordispeak' folder"
echo "3. Select 'Add Files to chordispeak'"
echo "4. Navigate to each file and add it"
echo "5. Make sure 'Add to target: chordispeak' is checked"
echo ""
echo "Files are located in: $(pwd)"
echo ""
echo "After adding files, also configure:"
echo "- Signing & Capabilities (select development team)"
echo "- Info.plist (add network security settings)"
echo ""
echo "See add_files_to_xcode.md for detailed instructions." 